### ISSUE TITLE
在flutter3.0.0 版本中， 项目报错

### ISSUE THREAD

**Issue by luwei888** [bytedance/flutter_ume#57]
## Steps to Reproduce 复现步骤

> Task :app:compileFlutterBuildDebug FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'D:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileFlutterBuildDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'D:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:414)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:205)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1170)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1165)
        at org.gradle.api.Project$exec$7.call(Unknown Source)
        at BaseFlutterTask.buildBundle(D:\src\flutter\packages\flutter_tools\gradle\flutter.gradle:1156)
        at BaseFlutterTask$buildBundle.callCurrent(Unknown Source)
        at FlutterTask.build(D:\src\flutter\packages\flutter_tools\gradle\flutter.gradle:1281)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)
        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:171)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:61)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:42)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:60)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:27)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:180)
        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
        at org.gradle.internal.Either$Right.fold(Either.java:175)
        at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:110)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:56)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:56)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:73)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:89)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:50)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:114)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:249)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:54)
        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
        at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:144)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)

**Comment by SheepYang1993** [comment]
+1

**Comment by chomoe327** [comment]
同样的错误

**Comment by dreamerldq** [comment]
maxLengthEnforced 已经被遗弃，导致报错
Error: No named parameter with the name 'maxLengthEnforced'.
../…/widget_detail_inspector/search_bar.dart:152
        maxLengthEnforced: false,

**Comment by luwei888** [comment]
> 
有修改方案吗？还是需要这个包的开发者更新？

**Comment by talisk** [comment]
> > 
> 
> 有修改方案吗？还是需要这个包的开发者更新？

@meng-fucius @dreamerldq @luwei888
 
兼容性测试正在进行中。卡在一个 pub 的空值异常问题上，马上就可以发出去版本了哈。感谢关注。

**Comment by talisk** [comment]
@meng-fucius @dreamerldq @luwei888 

flutter_ume 及其他插件的适配版本为 `1.0.0-dev.0`。欢迎试用。

The adaptation version of flutter_ume and other plugins is `1.0.0-dev.0`. Feel free to try it out.

**Comment by luwei888** [comment]
> @meng-fucius @dreamerldq @luwei888
> 
> flutter_ume 及其他插件的适配版本为 `1.0.0-dev.0`。欢迎试用。
> 
> The adaptation version of flutter_ume and other plugins is `1.0.0-dev.0`. Feel free to try it out.

I made a mistake

  flutter_ume: ^1.0.0-dev.0
  flutter_ume_kit_ui: ^1.0.0-dev.0
  flutter_ume_kit_device: ^1.0.0-dev.0
  flutter_ume_kit_perf: ^1.0.0-dev.0
  flutter_ume_kit_show_code: ^1.0.0-dev.0
  flutter_ume_kit_console: ^1.0.0-dev.0
  flutter_ume_kit_dio: ^1.0.0-dev.0

improve 1.0.0-dev.0  and pub get report error

Because flutter_ume_kit_dio >=1.0.0-dev.0 depends on flutter_ume ^1.0.0 which doesn't match any versions, flutter_ume_kit_dio >=1.0.0-dev.0 is forbidden.
So, because habit depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed.
pub get failed (1; So, because habit depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed.)

Is it just my fault ？

**Comment by wenboLee** [comment]
> > @meng-fucius @dreamerldq @luwei888
> > flutter_ume 及其他插件的适配版本为 `1.0.0-dev.0`。欢迎试用。
> > The adaptation version of flutter_ume and other plugins is `1.0.0-dev.0`. Feel free to try it out.
> 
> I made a mistake
> 
> flutter_ume: ^1.0.0-dev.0 flutter_ume_kit_ui: ^1.0.0-dev.0 flutter_ume_kit_device: ^1.0.0-dev.0 flutter_ume_kit_perf: ^1.0.0-dev.0 flutter_ume_kit_show_code: ^1.0.0-dev.0 flutter_ume_kit_console: ^1.0.0-dev.0 flutter_ume_kit_dio: ^1.0.0-dev.0
> 
> improve 1.0.0-dev.0 and pub get report error
> 
> Because flutter_ume_kit_dio >=1.0.0-dev.0 depends on flutter_ume ^1.0.0 which doesn't match any versions, flutter_ume_kit_dio >=1.0.0-dev.0 is forbidden. So, because habit depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed. pub get failed (1; So, because habit depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed.)
> 
> Is it just my fault ？

I use this code. it works. just will report warning.🙃

```
  flutter_ume: ^0.3.0+1
  flutter_ume_kit_ui:
    git:
      url: https://github.com/jiagengArctuition/flutter_ume
      path: kits/flutter_ume_kit_ui
  flutter_ume_kit_device: ^0.3.0
  flutter_ume_kit_perf: ^0.3.0
  flutter_ume_kit_show_code: ^0.3.0
  flutter_ume_kit_console: ^0.3.0
  flutter_ume_kit_dio: ^0.3.0
```
same ...

**Comment by SheepYang1993** [comment]
> > @meng-fucius @dreamerldq @luwei888
> > flutter_ume 及其他插件的适配版本为 `1.0.0-dev.0`。欢迎试用。
> > The adaptation version of flutter_ume and other plugins is `1.0.0-dev.0`. Feel free to try it out.
> 
> I made a mistake
> 
> flutter_ume: ^1.0.0-dev.0 flutter_ume_kit_ui: ^1.0.0-dev.0 flutter_ume_kit_device: ^1.0.0-dev.0 flutter_ume_kit_perf: ^1.0.0-dev.0 flutter_ume_kit_show_code: ^1.0.0-dev.0 flutter_ume_kit_console: ^1.0.0-dev.0 flutter_ume_kit_dio: ^1.0.0-dev.0
> 
> improve 1.0.0-dev.0 and pub get report error
> 
> Because flutter_ume_kit_dio >=1.0.0-dev.0 depends on flutter_ume ^1.0.0 which doesn't match any versions, flutter_ume_kit_dio >=1.0.0-dev.0 is forbidden. So, because habit depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed. pub get failed (1; So, because habit depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed.)
> 
> Is it just my fault ？

me too

**Comment by chomoe327** [comment]
> > @meng-fucius @dreamerldq @luwei888
> > flutter_ume 及其他插件的适配版本为 `1.0.0-dev.0`。欢迎试用。
> > The adaptation version of flutter_ume and other plugins is `1.0.0-dev.0`. Feel free to try it out.
> 
> I made a mistake
> 
> flutter_ume: ^1.0.0-dev.0 flutter_ume_kit_ui: ^1.0.0-dev.0 flutter_ume_kit_device: ^1.0.0-dev.0 flutter_ume_kit_perf: ^1.0.0-dev.0 flutter_ume_kit_show_code: ^1.0.0-dev.0 flutter_ume_kit_console: ^1.0.0-dev.0 flutter_ume_kit_dio: ^1.0.0-dev.0
> 
> improve 1.0.0-dev.0 and pub get report error
> 
> Because flutter_ume_kit_dio >=1.0.0-dev.0 depends on flutter_ume ^1.0.0 which doesn't match any versions, flutter_ume_kit_dio >=1.0.0-dev.0 is forbidden. So, because habit depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed. pub get failed (1; So, because habit depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed.)
> 
> Is it just my fault ？

just the same

**Comment by MiniOcean404** [comment]
我都无法启动

**Comment by miniocean404** [comment]
> > > @meng-fucius @dreamerldq @luwei888
> > > flutter_ume 及其他插件的适配版本为`1.0.0-dev.0`。欢迎
> > > 试用。flutter_ume等插件的适配版本为`1.0.0-dev.0`。随意尝试一下。
> > 
> > 
> > 我犯了一个错误
> > flutter_ume: ^1.0.0-dev.0 flutter_ume_kit_ui: ^1.0.0-dev.0 flutter_ume_kit_device: ^1.0.0-dev.0 flutter_ume_kit_perf: ^1.0.0-dev.0 flutter_ume_kit_show_code: ^1.0.0-dev.0 flutter_ume_kit_console: ^1.0.0-dev.0 flutter_ume_kit_dio: ^1.0.0-dev.0
> > 改进 1.0.0-dev.0 和 pub get 报告错误
> > 因为 flutter_ume_kit_dio >=1.0.0-dev.0 依赖于不匹配任何版本的flutter_ume ^1.0.0，所以flutter_ume_kit_dio >=1.0.0-dev.0 是被禁止的。所以，因为习惯依赖flutter_ume_kit_dio ^1.0.0-dev.0，版本求解失败。pub get failed (1; 所以，因为习惯依赖于flutter_ume_kit_dio ^1.0.0-dev.0，版本求解失败。)
> > 难道只是我的错？
> 
> 一样



> > > @meng-fucius @dreamerldq @luwei888
> > > flutter_ume 及其他插件的适配版本为`1.0.0-dev.0`。欢迎
> > > 试用。flutter_ume等插件的适配版本为`1.0.0-dev.0`。随意尝试一下。
> > 
> > 
> > 我犯了一个错误
> > flutter_ume: ^1.0.0-dev.0 flutter_ume_kit_ui: ^1.0.0-dev.0 flutter_ume_kit_device: ^1.0.0-dev.0 flutter_ume_kit_perf: ^1.0.0-dev.0 flutter_ume_kit_show_code: ^1.0.0-dev.0 flutter_ume_kit_console: ^1.0.0-dev.0 flutter_ume_kit_dio: ^1.0.0-dev.0
> > 改进 1.0.0-dev.0 和 pub get 报告错误
> > 因为 flutter_ume_kit_dio >=1.0.0-dev.0 依赖于不匹配任何版本的flutter_ume ^1.0.0，所以flutter_ume_kit_dio >=1.0.0-dev.0 是被禁止的。所以，因为习惯依赖flutter_ume_kit_dio ^1.0.0-dev.0，版本求解失败。pub get failed (1; 所以，因为习惯依赖于flutter_ume_kit_dio ^1.0.0-dev.0，版本求解失败。)
> > 难道只是我的错？
> 
> 我使用此代码。有用。只会报告警告。🙃
> 
> ```
>   flutter_ume: ^0.3.0+1
>   flutter_ume_kit_ui:
>     git:
>       url: https://github.com/jiagengArctuition/flutter_ume
>       path: kits/flutter_ume_kit_ui
>   flutter_ume_kit_device: ^0.3.0
>   flutter_ume_kit_perf: ^0.3.0
>   flutter_ume_kit_show_code: ^0.3.0
>   flutter_ume_kit_console: ^0.3.0
>   flutter_ume_kit_dio: ^0.3.0
> ```
> 
> 相同的 ...

+1

**Comment by serious198706** [comment]
可以暂时先用这种方式解决：
```
dependency_overrides:
  
  flutter_ume: ^1.0.0-dev.0
```

**Comment by talisk** [comment]
@meng-fucius @serious198706 @MiniOcean404 @wenboLee @SheepYang1993 @dreamerldq @luwei888 
`1.0.0` 正式版本已经发布，不再需要重写版本使用了。

**Comment by luwei888** [comment]
> @meng-fucius @serious198706 @MiniOcean404 @wenboLee @SheepYang1993 @dreamerldq @luwei888 `1.0.0` 正式版本已经发布，不再需要重写版本使用了。

很棒
